### ISSUE TITLE
console.log and app.listen ports do not match in app.js

### ISSUE THREAD

**Issue by MacTruck3-Code** [jaydestro/demo-app#4]
Working through your 'How to Launch a Dockerized Node.js App Using the Azure Web App for Containers Service' (awesome demo btw) and I was working through the steps for `npm start`. However, as I was doing `curl localhost:8000` the connection was failing. That's when I notice probably a typo in the following:

`app.listen(8080, function () {
  console.log('Example "Hello World" app listening on port 8000!');
});`

The port is listening on 8080, but in the article it states it should be port 8000 and the console.log references port 8000
Thanks for you hard work,
Clarence M.

**Comment by jaydestro** [comment]
### i missed this!  so sorry.  I've fixed it.
